databaseChangeLog:
  - changeSet:
      id: 1
      author: admin
      changes:
        - createTable:
            tableName: users
            ifNotExists: true
            columns:
              - column:
                  name: user_id
                  type: SERIAL
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: email
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: address
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: created_at
                  type: DATE
                  defaultValueComputed: CURRENT_DATE
              - column:
                  name: updated_at
                  type: DATE
                  defaultValueComputed: CURRENT_DATE
              - column:
                  name: status
                  type: VARCHAR(50)
                  constraints:
                    nullable: false
