docker pull mongo:latest
docker pull mysql:8.3.0
docker pull postgres:16.3
docker pull liquibase/liquibase:latest
docker pull confluentinc/cp-zookeeper:7.5.0
docker pull confluentinc/cp-kafka:7.5.0
docker pull confluentinc/cp-schema-registry:7.5.0
docker pull provectuslabs/kafka-ui:latest
docker pull mysql:8
docker pull quay.io/keycloak/keycloak:24.0.1
docker pull grafana/loki:main
docker pull prom/prometheus:v2.54.1
docker pull grafana/tempo:latest
docker pull grafana/grafana:latest