server:
  port: 8080

spring:

  application:
    name: user-service


  datasource:
    url: jdbc:postgresql://postgres.default.svc.cluster.local:5432/users

    username: postgres
    password: root123
    initialization-mode: always
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    sql:
      init:
        mode: always
      datasource:
        initialization-mode: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: user-service
  tracing:
    sampling:
      probability: 1.0


loki:
  url: http://localhost:3100/loki/api/v1/push

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

app:
  config:
    keycloak:
      auth-server-url: http://keycloak.default.svc.cluster.local:8080
      realm: banking-realm-security
      resource: api-client
      credentials:
        secret: 2ehXekEgkPWklJcjBdLpMduPpaOxDJWg