apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-payment-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mongodb-payment

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-payment-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-payment-secrets
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=
  MONGO_INITDB_DATABASE: cGF5bWVudHM=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-payment
  template:
    metadata:
      labels:
        app: mongodb-payment
    spec:
      containers:
        - name: mongo-payment
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-payment-secrets
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-payment-secrets
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongodb-payment-secrets
                  key: MONGO_INITDB_DATABASE
          volumeMounts:
            - name: mongo-payment-data
              mountPath: /data/db
      volumes:
        - name: mongo-payment-data
          persistentVolumeClaim:
            claimName: mongodb-payment-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-payment
spec:
  selector:
    app: mongodb-payment
  ports:
    - protocol: TCP
      port: 27018
      targetPort: 27017
  type: ClusterIP
