databaseChangeLog:
  - changeSet:
      id: 2
      author: admin
      preConditions:
        onFail: MARK_RAN
        onError: MARK_RAN
        not:
          tableExists:
            tableName: Accounts
      changes:
        - createTable:
            tableName: Accounts
            columns:
              - column:
                  name: Account_ID
                  type: VARCHAR(20)
                  constraints:
                    primaryKey: true
              - column:
                  name: Account_Type
                  type: VARCHAR(50)
                  constraints:
                    nullable: false
              - column:
                  name: Balance
                  type: DECIMAL(15, 2)
                  constraints:
                    nullable: false
              - column:
                  name: Status
                  type: VARCHAR(20)
                  constraints:
                    nullable: false
              - column:
                  name: Created_At
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
              - column:
                  name: Updated_At
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false
              - column:
                  name: User_Email
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
